#cloud-config

runcmd:
- [touch, /root/cloud-init-worked]

timezone: Europe/Kiev

users:
  - name: stream
    groups: users, admin, sudo
    gecos: VM Control User
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB4PmWN0Ipp8dllqr66Vf3TRoq7Sx+hf1QfD7fAGwIl0 vm-service
      - ssh-ed25519 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOxnANuMT7aImxlfYFDEhwtlVibT/TIwojZ56pnC65cZ/GRtviQ8vYpW2qbKwUONpV1O+uwHtmtBQLTfTINa7K2yHZLcXo8Qzsx1sQ94JuqKzLu0IRnJAGaiuP9f2ffysHnaJsHj2YSqKhXAgnvPa/w6asAjBeZM7D8h3Scuj4YGEsuNE6KrjbSASAPo3tRnXoegjCegN1saSyONUL58IP+LltnDDfCeRK6nZZLsMkWyOJrwtgqil94wpSKJ59jP29gZfQKHnFQgMIOyVTJclHxZ6XyAJPo/R26/nDhzqx92MH7rvd4XFwKHVme0qkpIsa2FYQQd5Daqu84D5qqkbmkaBoyPqhn+537HuIfcdV0aP3LvEYzSpG/vJ/WJ27Ru7qYuV9CQlW74RhMmnSXXInMjmp5TzbGHQrpVfioOdE65H68+xDTTgpT1f53yjmtE0A04rl9pJod2c/wIkV3+N7DYFbI7PVNMZPSbCIQSlynGwXhZyIOnQvW231JZEnRR8= amukhsimov@dell
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwIUEnpG/EA7jCfZLYkxEb1gEhizO3/eS8h+5o/9j/s service_automation
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHkIrLqlL9AloMwoQZ9NfkIeAIXRmMHFt782bXLjVcNU serhii@MacBook-Pro-3
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQjnrhr3/2sOkqm6ov/54hqtE0sXcFxYG1RUc6o5h8HCWeojNinA6XTZEVPQ8ODRT7sGXh2PtXepn/eT7Haepys7BUBS9iWb7Q23RqcQQ3+VnE7ewZ0gBhAe84ExaNVq+/ZBvzdWQ9f+DIwIe+yttY0ja/v2eKMmTtbF9kEcXm8430SkRKBLAr2OGEjeC/2EC7I4ChSmqgDWKLej5UVK8IP7icsjw3WMfu1ko0+jxMM1Wjumc5XAsH5PeZASYEftICmoK0o38gxytpBDqSMGGI9GCSsU5ss3v7gvwke02s/mKxM+9xRuCE4E////0p3DnOGkV//hfE1lMQq8nT85huDr2ummSgiQwlEMo8Bkvsfns+LSeKPYeZ3VDWFdmmNd0wFO/tbYauDsD458PEGwqz4us/YpftvA1ns9+FSfvJhX/UZxnMem7rVDyAn0Cew1h1ziku/MO1trWm7dl+sIIvdkcqo4YIQk6UzrjN4+GSHZnVpKg9v0k0FXWUQ7Yka/s= macbook@jurilents
    lock_passwd: false

# Add OBS ppa repo
apt:
  sources:
    obsproject.list:
      source: "ppa:obsproject/obs-studio"

packages:
  - curl
  - ffmpeg
  - git
  - icewm
  - libmng2
  - mc
  - neovim
  - pavucontrol
  - python3-pip
  - python3-testresources
  - qt5-image-formats-plugins
  - ranger
  - tmux
  - wget
  - x11vnc
  - xcb
  - xvfb
  - libspa-0.2-modules
  - libv4lconvert0
  - libmbedcrypto7
  - libmbedtls14
  - libmbedx509-1
  - libpipewire-0.3-0
  - libqt5xml5
  - libv4l-0
  # - [obs-studio, 27.1.3-0obsproject1~hirsute]

runcmd:
 - mkdir -p /home/stream/.config/
 - mkdir -p /home/stream/.ssh/
 - mkdir -p /home/stream/ts
 - mkdir -p /opt/stream-services
 - mkdir -p /lib/systemd/system/stream
 - echo 'set -o vi' >> /home/stream/.bashrc
 - echo 'export EDITOR=nvim' >> /home/stream/.bashrc
 - echo 'set -o vi' >> /root/.bashrc
 - echo 'export EDITOR=nvim' >> /root/.bashrc
 - wget http://mirrors.kernel.org/ubuntu/pool/universe/o/obs-studio/obs-studio_27.2.3+dfsg1-1_amd64.deb
 - wget http://mirrors.kernel.org/ubuntu/pool/universe/o/obs-studio/libobs0_27.2.3+dfsg1-1_amd64.deb
 - wget http://mirrors.kernel.org/ubuntu/pool/universe/o/obs-studio/obs-plugins_27.2.3+dfsg1-1_amd64.deb
 - wget https://github.com/obsproject/obs-websocket/releases/download/4.9.1/obs-websocket_4.9.1-1_amd64.deb
 - sudo dpkg -i libobs0_27.2.3+dfsg1-1_amd64.deb
 - sudo dpkg -i obs-plugins_27.2.3+dfsg1-1_amd64.deb
 - sudo dpkg -i obs-studio_27.2.3+dfsg1-1_amd64.deb
 - sudo dpkg -i obs-websocket_4.9.1-1_amd64.deb
 - apt -f install -y
 - chown -R stream:stream /home/stream
 - chown -R stream:stream /opt/stream-services
 - sudo -u stream bash -c 'wget https://files.teamspeak-services.com/releases/client/3.5.6/TeamSpeak3-Client-linux_amd64-3.5.6.run -O /home/stream/ts.run'
 - sudo -u stream bash -c 'chmod +x /home/stream/ts.run'
 - sudo -u stream bash -c '/home/stream/ts.run --tar -xf -C /home/stream/ts'
 - sudo -u stream bash -c 'git clone https://github.com/ALLATRA-IT/cloudobs.git /opt/stream-services/cloudobs'
 - sudo -u stream bash -c 'cd /opt/stream-services/cloudobs; pip3 install -r requirements.txt'
 - git clone https://github.com/amukhsimov/gdown.git && cd gdown && pip install .
 - touch /DONE
 # - reboot

package_update: true
package_upgrade: true

